services:
  database:
    image: pgvector/pgvector:pg16
    container_name: finguard-database
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-finguard}
      POSTGRES_USER: ${POSTGRES_USER:-finguard}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-local-development-password}

    ports:
      - "5432:5432"

    volumes:
      - finguard_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-finguard} -d ${POSTGRES_DB:-finguard}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  finguard_postgres_data:
